### PR TITLE
Fix ground pounding moving platforms

### LINKED ISSUE #177: Unable to reach semi-solid platforms with a ground pound
**Describe the bug**
Looks like Mario can reach the semi-solid platforms with a ground pound, but it's just only an animation, so it doesn't actually increases the height.

**To Reproduce**
Try barely reaching the semi-solid platforms with a ground pound as you can see in the video here:

https://github.com/GTcreyon/SM63Redux/assets/13905392/5a0755c6-89c1-4187-a2c5-57f534ae34dd

**Expected behavior**
Mario/player should land on any semi-solid platforms with a ground pound to gain a little bit more height.

**System Information**
 - OS/Browser: Windows 10 / Avast Secure Browser (version 113.0.21244.127 (Official Build) (64-bit))
 - Game version: v0.1.6.alpha

### LINKED ISSUE #179: Ground pound cancelation by landing moving platforms early
**Describe the bug**
It's possible to cancel the beginning part of a ground pound animation by touching any moving platform before actually landing it from the ground pound action, preventing it from breaking it (if there's any moving platform that can be broken with a ground pound).

**Video on how to reproduce (make sure to turn on sound)**

https://github.com/GTcreyon/SM63Redux/assets/13905392/e78330a2-4be6-4906-af28-268b7d0c861b

**Expected behavior**
Ground pound action shouldn't get canceled if touched by a moving platform early.

**System Information**
 - OS/Browser: Windows 10 / Avast Secure Browser (version 113.0.21244.127 (Official Build) (64-bit))
 - Game version: v0.1.6.alpha

**Additional context**
You can also cancel it with semi-solid platforms that are not moving if you time it right.
I'm not sure if this could be a feature or not.

### PR DESCRIPTION
**Pull request by Kuma-Boo**
# Description of changes

~~Removes the wind-up from character_sprite.gd (If we really want this effect, it should be implemented by actually moving the character instead of just the sprite, so physics can remain consistent)~~
Fixes the order of processing ground pound inputs. SIRIUS: This makes ground pounds work correctly on moving platforms.

# Issue(s)

Closes #179

### CODE REVIEW

**Comment by Koopa1018** [comment]
This does make sense as a fix. I added the wind-up because it really does make the pound feel more impactful, and I feel like removing it would hurt the gameplay experience.

You mentioned moving the player instead of the sprite...I've also been thinking that would be a good way to do it. I'll see if I can get that implemented.

**Comment by jaschutte** [comment]
I agree, moving the player character would probably be the best way to handle this, could you add that functionality into this PR?

**Review by Koopa1018 — CHANGES_REQUESTED** [review]
Tell you what: go ahead and revert all the pound windup changes. I'll fix that problem myself.

**Comment by Koopa1018** [comment]
Scratch that. Windup changes have been reverted. Rest of it is ready for review....

**Review by Koopa1018 — APPROVED** [review]
Platform fix confirmed good. #179 no longer occurs.

**Pull request merged**
