### PR TITLE
New player sprites and animations

### LINKED ISSUE #109: Move player sprite handling to its own script
**Describe the feature you'd like**
Move code that handles the player sprite out of player.gd and into its own script. This would simplify the player script drastically, and the new script could be written to facilitate more complex animations.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
Yes, I will likely do so in order to implement the new Mario sprites.

### PR DESCRIPTION
**Pull request by GTcreyon**
# Description of changes
Implements Shima's new animations for Mario. Includes lots of improvements to when and how these animations are executed. Handling of animations is split into its own script, separate from `player.gd`, making another step towards simplifying it.

# Issue(s)
Closes #109

### CODE REVIEW

**Review by RandomCatDude — APPROVED** [review]
i like it, there's just one minor issue that i spotted
there's a one-frame bug when entering the dive state while grounded, the sprite appears higher than it should be:
image

it's pretty negligible imo so i think if it can't be fixed, it's fine to merge regardless

**Comment by Koopa1018** [comment]
WHoa hold up update's not finished
we should revert this to a draft PR

**Comment by GTcreyon** [comment]
> WHoa hold up update's not finished we should revert this to a draft PR (is...is that possible?)

Done. All of the sprites were fully implemented, but I suppose it was a little hasty to do it immediately without proper testing.

**Comment by Koopa1018** [comment]
I was referring to the FLUDD sprite update....

**Comment by Koopa1018** [comment]
Ahhh, ok... probably good to merge, then 😅 my bad

**Comment by Koopa1018** [comment]
(Is it intended that the backflip have no transition to falling?)

**Comment by GTcreyon** [comment]
> (Is it intended/okay that the backflip has no transition to falling?)
> 
> (EDIT: yeah, let's just leave that for a future PR.)

No, not intentional.

**Pull request merged**
