### PR TITLE
Make menus easier to fully access

### PR DESCRIPTION
**Pull request by GTcreyon**
# Description of changes
- Options menu now has a full scroller
- Pause menu close button properly visible
- Feedback menu close button properly visible

### CODE REVIEW

**Review by RandomCatDude — APPROVED** [review]
looks good

the scaling while not in-game makes it a bit claustrophobic but that seems like a separate issue

**Comment by jaschutte** [comment]
> looks good
> 
> the scaling while not in-game makes it a bit claustrophobic but that seems like a separate issue

(Feel free to merge once it's approved)

**Comment by GTcreyon** [comment]
> looks good
> 
> the scaling while not in-game makes it a bit claustrophobic but that seems like a separate issue

I don't fully understand what you mean by that.

**Comment by RandomCatDude** [comment]
> I don't fully understand what you mean by that.

in main menu:
image

VS while in-game
image


... but looking at it again, it seems fullscreening via F4 (bringing the game into full 1920x1080 on my system), actually results in both scenarios having the former's scaling... not sure what's up with that, but it seems like something best addressed separately

**Comment by GTcreyon** [comment]
I understand now. This is a general point about the game's scaling, I think.

**Pull request merged**
