### PR TITLE
Fix dialog box not showing on large windows

### LINKED ISSUE #95: Dialogue boxes disappear on certain resolutions
**Describe the bug**
On large resolutions, the text dialogue box displayed when reading a sign or talking to an NPC disappears.

**To Reproduce**
Fullscreen the game, and read a sign.

**Expected behavior**
The box should be properly visible and properly scaled.

**Screenshots**
image

**System Information**
 - OS/Browser: Windows
 - Game version: v0.1.6.RC1
 - Other specs: 1920x1080 monitor

### PR DESCRIPTION
**Pull request by GTcreyon**
# Description of changes
Fix for #95

# Issue(s)
Closes #95

### CODE REVIEW

**Review by Koopa1018 — CHANGES_REQUESTED** [review]
Looks mostly fine to me. Box does hang out on the left side of the screen when the window is resized:
image

**Comment by GTcreyon** [comment]
> Looks mostly fine to me. Box does hang out on the left side of the screen when the window is resized:

Oops. I'll fix that.

**Comment by GTcreyon** [comment]
Bump. Would be nice to merge.

**Review by Koopa1018 — APPROVED** [review]

**Comment by Koopa1018** [comment]
@brickblock369 says it's working, and I trust him, so. Approved

**Pull request merged**
