### PR TITLE
Fix main menu item description misalignment

### PR DESCRIPTION
**Pull request by GTcreyon**
# Description of changes
The descriptions on the main menu had misconfigured control alignments. This fixes that.

### CODE REVIEW

**Comment by GTcreyon** [comment]
Oops, that's not right. Shouldn't be merging into `master`.

**Comment by GTcreyon** [comment]
Fixed.

**Review by Koopa1018 — CHANGES_REQUESTED** [review]
Nice, I thought centering would be the right call here. Vertical centering seems off, though: the text runs up against the bottom of the box.

**Comment by GTcreyon** [comment]
> Nice, I thought centering would be the right call here. Vertical centering seems off, though: the text runs up against the bottom of the box.

That's normal - its always been like that.

**Review by Koopa1018 — APPROVED** [review]

**Pull request merged**
