### PR TITLE
Fix back button scaling

### PR DESCRIPTION
**Pull request by GTcreyon**
# Description of changes
Fix an issue where the tappable back buttons on some menus scale poorly

### CODE REVIEW

**Comment by Koopa1018** [comment]
This problem wasn't caused by the 4.1 update, so I'm going to untag for that.

**Comment by Koopa1018** [comment]
Oh yes--sounds like this also fixes #207.

**Comment by GTcreyon** [comment]
I don't think this was caused by 4.1.
Here's how it looks without the fixes:

**Comment by Koopa1018** [comment]
Ahhh...giant in the pause menu, tiny in the options menu. Gotcha.

**Review by AidenBeresford — APPROVED** [review]
Looks good to me, I don't see how these changes could have any drawbacks. I'm going to approve, but it might still be good for someone else to review as well. Up to you.

**Pull request merged**
