### PR TITLE
Update project to Godot 4.1

### PR DESCRIPTION
**Pull request by Koopa1018**
# Description of changes
Upgrades the project to run properly in Godot 4.1. As many bugs as we could find have been fixed. The project is mostly working now, but not all features have been tested (I only just realized there's fullscreen controls, for example).

### CODE REVIEW

**Comment by jaschutte** [comment]
I think we should consider merging this into main sometime soon, we've been working on this for a long time. I say we merge current PRs and then we double check if this hasn't broken anything. If all is clear, we merge this into main.

**Comment by GTcreyon** [comment]
I fear the merge conflicts that may soon arise.

**Comment by Koopa1018** [comment]
I've been doing my best to merge `master` anytime somebody pushes to it. Hopefully, that means most of the conflicts should already be resolved....

**Comment by jaschutte** [comment]
Once #266 is merged, the main game is stable without any notable issues on x86_64 Linux.
Will check on android and web soon.

**Comment by jaschutte** [comment]
Tested the web version, nothing broken there either.

However mario's movement was stuttery, though that may just be the web version acting weird. Would be nice to have someone confirm this though.

**Comment by GTcreyon** [comment]
> However mario's movement was stuttery, though that may just be the web version acting weird. Would be nice to have someone confirm this though.

See issue #268 - this happens on all platforms.

**Comment by jaschutte** [comment]
I keep pressing  that button on accident, sorry!!!!

**Comment by GTcreyon** [comment]
> I keep pressing that button on accident, sorry!!!!

No worries.

Tangentially, I'm wondering if it's worth fixing the regressions on this PR, or simply merging it and fixing them as part of the overall project development. As far as I can tell, there's no longer any *major* issues like crashes to resolve, and it seems reasonable to get everything onto master so that development can be centralized again. We're already all our PRs on the 4.1 branch, so I don't see a serious issue in merging.

(We should probably do a few more platform tests though, just to be safe.)

**Comment by jaschutte** [comment]
I agree, I think it's time we should merge this with main.
Any bugs which arise we can solve then.

I've tested web and linux desktop, could you test on android? Then we just need a mac build tested and we're all good I'd say.

**Comment by GTcreyon** [comment]
> I've tested web and linux desktop, could you test on android?
#269, otherwise fine.

**Comment by jaschutte** [comment]
> > I've tested web and linux desktop, could you test on android?
> > #269, otherwise fine.

I feel that we can fix that post merge

**Review by jaschutte — APPROVED** [review]
The time has come

The beast will be released!

**Comment by Kwonunn** [comment]
woot

**Pull request merged**
