### PR TITLE
Add exit menu to pause screen

### LINKED ISSUE #43: Proper "EXIT" button in the Pause Menu, to exit to the Title Screen.
**Describe the feature you'd like**
An easy way to exit to the title screen. Right now, the only way to do this is restarting the entire game.

**Do you intend to contribute this yourself? If so, how do you plan on doing it?**
I don't know too much about coding yet (I want to, this kind of thing is my dream job), so no.

**Additional context**
[What it looks like now, and how annoying it is to refresh every time.](https://user-images.githubusercontent.com/83524620/213223433-0e585786-8a22-4701-91b5-0572ebcec88c.webm)
Just a simple button to return to the title screen in the "Exit" section of the Pause menu would be fine until the Pause menus are fixed.
You could even just rip the image from the original game!

### PR DESCRIPTION
**Pull request by Koopa1018**
# Description of changes
Fills the exit menu with working buttons. Layout is adapted from the mockup shared in the `art` channel.

The "Exit Level" button is grayed out, for obvious reasons. If you could click it, it would call a function, but the function isn't complete (again for obvious reasons), so in all likelihood the game would just crash.

The "Close Game" button is designed to not appear on mobile or web builds. I never figured out how to export builds, so I haven't been able to test this.

Still need a sound to play when a button is pressed. Probably a complement to the existing "start game" sound.

# Issue(s)
Closes #43

### CODE REVIEW

**Comment by GTcreyon** [comment]
Are they meant to lay out like this? On the edge, rather than the center?
image


And how about this scaling?
image

**Comment by GTcreyon** [comment]
Similar issue.
image

Note that this is on the Web version. The correct string is "HTML5", not "Web".

**Comment by Koopa1018** [comment]
🤦 
I forgot to change it to HTML5
Dangit Godot documentation update

Anyway, the edge-aligned layout and scaling were intentional, but I concede that the scaled version doesn't look very good. I could switch to centered pipes, given a bit of time.

**Comment by Koopa1018** [comment]
Arright, ready for review again.

Default res:
Super Mario 63 Redux (DEBUG) 3_15_2023 1_06_36 PM
Scaled up:
Super Mario 63 Redux (DEBUG) 3_15_2023 1_06_44 PM
Scaled down:
Super Mario 63 Redux (DEBUG) 3_15_2023 1_09_46 PM

**Comment by Koopa1018** [comment]
Applied the requested changes:
- Made the pipes expand outward instead of shift left.
- Consolidated similar themes into single theme with variations. (Single- and double-sided pipe are separate themes still--should keep us from needing to load too much unused graphic data.)

**Comment by Koopa1018** [comment]
3 weeks later, I can't even remember what I was worried about. Current setup looks good. You think it's ready?

**Review by GTcreyon — APPROVED** [review]

**Pull request merged**
